### ISSUE TITLE
Freeing up memory

### ISSUE THREAD

**Issue by ddayan** [ender672/ruby-vips#4]
Just wondering if there's a possibility to free the memory (like the RMagick destroy function). I couldn't find anything like that on the rdocs.

**Comment by ender672** [comment]
VIPS does not keep anything in memory unless it is processing an image.

This means there is no need to "free" anything -- a ruby-vips Image object uses no more memory than any other ruby object and gets cleaned up on GC.

More info on how VIPS works is here:
http://www.vips.ecs.soton.ac.uk/index.php?title=How_it_works

**Comment by ddayan** [comment]
It hugs my memory (I don't know why) so I'm nulling my variables and using GC.start. Thats not an ideal solution, but most likely the only one.

**Comment by ender672** [comment]
Can you paste a sample of code that is using too much memory?

**Comment by catwell** [comment]
I do the same as ddayan (using GC.start). That forces the GC to collect the memory and I think it is a good idea.

Depending on the OS, simply processing lots of images one after another in the same process can eat lots of memory, and this will become a problem if you do that in several independent processes at the same time. That's because the Ruby GC (in MRI) doesn't care about free memory but only about memory it uses, so independent processes running independent MRI instances don't "see" each other.

Anyway, the conclusion is: explicitly call GC.start when you're done processing an image and you should be fine.

**Comment by jcupitt** [comment]
libvips can use lots of memory in some circumstances.

If you open an image in a format that supports random access, such as tiled tiff, OpenEXR or vips, libvips will process directly from the disc file and use very little memory. However, some formats, such as JPEG, do not support efficient random access and need to be completely decompressed before they can worked on.

Faced with a non-random access file, libvips 7.22 and earlier will allocate a large memory buffer and decompress to that. Further processing uses little memory, but you will need enough memory for the initial file. You can override this mechanism with your own code if you wish. The memory is freed when the image is closed.

libvips 7.24 and later have a new open mode which goes via a temporary disc file instead. The source image is decompressed to a temporary vips image, then processing is done directly from the disc file. Again, you can override this mechanism with your own code if you wish. The file is deleted when the image is closed.

So ... 7.24 and later will never use much memory (a few 10s of MB during processing, only a few kb per image when idle), but may cause a spike of disc IO. And of course, it might leave some large files if you crash during an operation, argh.

A more serious problem than running out of memory is running out of file ids. Most open image files will use up a file id and many platforms only allow a program to use 1000 of these at once.
